
---


- hosts: localhost
  become: yes
  vars:
    ansible_ssh_pass:

  tasks:
    - name: create directory named "thenewone"
      file:
        path: /home/lilit/Desktop/Project/thenewone
        state: directory
        mode: '0777'

    - name: Install Paramiko using pip
      pip:
        name: paramiko
        executable: pip3
        state: latest
